// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IndigoServiceClient is the client API for IndigoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndigoServiceClient interface {
	GetRole(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (*Role, error)
	InsertRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*BoolValue, error)
	AddRolePermission(ctx context.Context, in *AddRolePermissionRequest, opts ...grpc.CallOption) (*AddRolePermissionResponse, error)
	RemoveRolePermission(ctx context.Context, in *RemoveRolePermissionRequest, opts ...grpc.CallOption) (*RemoveRolePermissionResponse, error)
	GetUserRoles(ctx context.Context, in *GetUserRolesRequest, opts ...grpc.CallOption) (*GetUserRolesResponse, error)
	AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error)
	RemoveUserRole(ctx context.Context, in *RemoveUserRoleRequest, opts ...grpc.CallOption) (*RemoveUserRoleResponse, error)
	AddUserPermission(ctx context.Context, in *AddUserPermissionRequest, opts ...grpc.CallOption) (*AddUserPermissionResponse, error)
	RemoveUserPermission(ctx context.Context, in *RemoveUserPermissionRequest, opts ...grpc.CallOption) (*RemoveUserPermissionResponse, error)
}

type indigoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndigoServiceClient(cc grpc.ClientConnInterface) IndigoServiceClient {
	return &indigoServiceClient{cc}
}

func (c *indigoServiceClient) GetRole(ctx context.Context, in *StringValue, opts ...grpc.CallOption) (*Role, error) {
	out := new(Role)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/GetRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) InsertRole(ctx context.Context, in *Role, opts ...grpc.CallOption) (*BoolValue, error) {
	out := new(BoolValue)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/InsertRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) AddRolePermission(ctx context.Context, in *AddRolePermissionRequest, opts ...grpc.CallOption) (*AddRolePermissionResponse, error) {
	out := new(AddRolePermissionResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/AddRolePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) RemoveRolePermission(ctx context.Context, in *RemoveRolePermissionRequest, opts ...grpc.CallOption) (*RemoveRolePermissionResponse, error) {
	out := new(RemoveRolePermissionResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/RemoveRolePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) GetUserRoles(ctx context.Context, in *GetUserRolesRequest, opts ...grpc.CallOption) (*GetUserRolesResponse, error) {
	out := new(GetUserRolesResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/GetUserRoles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) AddUserRole(ctx context.Context, in *AddUserRoleRequest, opts ...grpc.CallOption) (*AddUserRoleResponse, error) {
	out := new(AddUserRoleResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/AddUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) RemoveUserRole(ctx context.Context, in *RemoveUserRoleRequest, opts ...grpc.CallOption) (*RemoveUserRoleResponse, error) {
	out := new(RemoveUserRoleResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/RemoveUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) AddUserPermission(ctx context.Context, in *AddUserPermissionRequest, opts ...grpc.CallOption) (*AddUserPermissionResponse, error) {
	out := new(AddUserPermissionResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/AddUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indigoServiceClient) RemoveUserPermission(ctx context.Context, in *RemoveUserPermissionRequest, opts ...grpc.CallOption) (*RemoveUserPermissionResponse, error) {
	out := new(RemoveUserPermissionResponse)
	err := c.cc.Invoke(ctx, "/protos.IndigoService/RemoveUserPermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndigoServiceServer is the server API for IndigoService service.
// All implementations must embed UnimplementedIndigoServiceServer
// for forward compatibility
type IndigoServiceServer interface {
	GetRole(context.Context, *StringValue) (*Role, error)
	InsertRole(context.Context, *Role) (*BoolValue, error)
	AddRolePermission(context.Context, *AddRolePermissionRequest) (*AddRolePermissionResponse, error)
	RemoveRolePermission(context.Context, *RemoveRolePermissionRequest) (*RemoveRolePermissionResponse, error)
	GetUserRoles(context.Context, *GetUserRolesRequest) (*GetUserRolesResponse, error)
	AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error)
	RemoveUserRole(context.Context, *RemoveUserRoleRequest) (*RemoveUserRoleResponse, error)
	AddUserPermission(context.Context, *AddUserPermissionRequest) (*AddUserPermissionResponse, error)
	RemoveUserPermission(context.Context, *RemoveUserPermissionRequest) (*RemoveUserPermissionResponse, error)
	mustEmbedUnimplementedIndigoServiceServer()
}

// UnimplementedIndigoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIndigoServiceServer struct {
}

func (UnimplementedIndigoServiceServer) GetRole(context.Context, *StringValue) (*Role, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRole not implemented")
}
func (UnimplementedIndigoServiceServer) InsertRole(context.Context, *Role) (*BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertRole not implemented")
}
func (UnimplementedIndigoServiceServer) AddRolePermission(context.Context, *AddRolePermissionRequest) (*AddRolePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRolePermission not implemented")
}
func (UnimplementedIndigoServiceServer) RemoveRolePermission(context.Context, *RemoveRolePermissionRequest) (*RemoveRolePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveRolePermission not implemented")
}
func (UnimplementedIndigoServiceServer) GetUserRoles(context.Context, *GetUserRolesRequest) (*GetUserRolesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRoles not implemented")
}
func (UnimplementedIndigoServiceServer) AddUserRole(context.Context, *AddUserRoleRequest) (*AddUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserRole not implemented")
}
func (UnimplementedIndigoServiceServer) RemoveUserRole(context.Context, *RemoveUserRoleRequest) (*RemoveUserRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserRole not implemented")
}
func (UnimplementedIndigoServiceServer) AddUserPermission(context.Context, *AddUserPermissionRequest) (*AddUserPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserPermission not implemented")
}
func (UnimplementedIndigoServiceServer) RemoveUserPermission(context.Context, *RemoveUserPermissionRequest) (*RemoveUserPermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveUserPermission not implemented")
}
func (UnimplementedIndigoServiceServer) mustEmbedUnimplementedIndigoServiceServer() {}

// UnsafeIndigoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndigoServiceServer will
// result in compilation errors.
type UnsafeIndigoServiceServer interface {
	mustEmbedUnimplementedIndigoServiceServer()
}

func RegisterIndigoServiceServer(s grpc.ServiceRegistrar, srv IndigoServiceServer) {
	s.RegisterService(&IndigoService_ServiceDesc, srv)
}

func _IndigoService_GetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).GetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/GetRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).GetRole(ctx, req.(*StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_InsertRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Role)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).InsertRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/InsertRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).InsertRole(ctx, req.(*Role))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_AddRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).AddRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/AddRolePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).AddRolePermission(ctx, req.(*AddRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_RemoveRolePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRolePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).RemoveRolePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/RemoveRolePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).RemoveRolePermission(ctx, req.(*RemoveRolePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_GetUserRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).GetUserRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/GetUserRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).GetUserRoles(ctx, req.(*GetUserRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_AddUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).AddUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/AddUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).AddUserRole(ctx, req.(*AddUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_RemoveUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).RemoveUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/RemoveUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).RemoveUserRole(ctx, req.(*RemoveUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_AddUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).AddUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/AddUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).AddUserPermission(ctx, req.(*AddUserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndigoService_RemoveUserPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndigoServiceServer).RemoveUserPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.IndigoService/RemoveUserPermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndigoServiceServer).RemoveUserPermission(ctx, req.(*RemoveUserPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndigoService_ServiceDesc is the grpc.ServiceDesc for IndigoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndigoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.IndigoService",
	HandlerType: (*IndigoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRole",
			Handler:    _IndigoService_GetRole_Handler,
		},
		{
			MethodName: "InsertRole",
			Handler:    _IndigoService_InsertRole_Handler,
		},
		{
			MethodName: "AddRolePermission",
			Handler:    _IndigoService_AddRolePermission_Handler,
		},
		{
			MethodName: "RemoveRolePermission",
			Handler:    _IndigoService_RemoveRolePermission_Handler,
		},
		{
			MethodName: "GetUserRoles",
			Handler:    _IndigoService_GetUserRoles_Handler,
		},
		{
			MethodName: "AddUserRole",
			Handler:    _IndigoService_AddUserRole_Handler,
		},
		{
			MethodName: "RemoveUserRole",
			Handler:    _IndigoService_RemoveUserRole_Handler,
		},
		{
			MethodName: "AddUserPermission",
			Handler:    _IndigoService_AddUserPermission_Handler,
		},
		{
			MethodName: "RemoveUserPermission",
			Handler:    _IndigoService_RemoveUserPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/indigo.proto",
}
